EcoKids/EcoKids/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EcoKids_Integracao.urls')),
]

EcoKids/EcoKids_Integracao/urls.py
from django.urls import path
from . import views

app_name = 'EcoKids_Integracao'

urlpatterns = [
    path('', views.index, name='HomePage'),
    path('quem-somos/', views.QuemSomos, name='QuemSomos'), 
    path('login/', views.Login, name='Login'), 
    path('Personagem/', views.Personagem, name='Personagem'), 
    path('Card/', views.Card, name='Card'), 
    path('login2/', views.Login2, name='Login2'),
    path('signup/', views.signup, name='signup'),
    path('ToDoList/', views.ToDoList, name='ToDoList'),
    path('Mural/', views.Mural, name='Mural'),
    path('AdicionarComentario/', views.mural_comentario, name='AdicionarComentario'),
    path('logout/', views.logout, name='logout'),
    path('get_avatar_url/', views.get_avatar_url, name='get_avatar_url'),
    path('Ranking/', views.Ranking, name='Ranking'),
    path('marcar-tarefa-realizada/<int:tarefa_id>/', views.marcar_tarefa_realizada, name='marcar_tarefa_realizada'),
    path('api/get-ranking-data/', views.get_ranking_data, name='get_ranking_data'),
    path('get_tempo_restante/', views.get_tempo_restante, name='get_tempo_restante'),
    path('generate_nonce/', views.generate_nonce, name='generate_nonce'),
    path('Mural_Nonce/', views.Mural_Nonce, name='Mural_Nonce'),
    path('Card_Nonce/', views.Card_Nonce, name='Card_Nonce'),
    path('HomePage_Nonce/', views.HomePage_Nonce, name='HomePage_Nonce'),
    path('Personagem_Nonce/', views.Personagem_Nonce, name='Personagem_Nonce')
    # path('Login_Nonce/', views.Login_Nonce, name='Login_Nonce')
]

EcoKids/EcoKids_Integracao/models.py
# models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Usuario(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=128)
    personagem_selecionado = models.CharField(max_length=100, blank=True, null=True)
    avatar_data_id = models.CharField(max_length=100, blank=True, null=True)  
    avatar_url = models.CharField(max_length=255, blank=True, null=True)  
    total_pontuacao = models.IntegerField(default=0) 

    def __str__(self):
        return self.nome  

class Forum(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=40)
    comentario = models.TextField(max_length=500)
    data_hora = models.DateTimeField(auto_now_add=True)
    curtidas = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo

class Tarefa(models.Model):
    # usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)  
    descricao = models.CharField(max_length=255, null=True) 
    pontuacao = models.IntegerField(default=0, null=True) 
    realizada = models.BooleanField(default=False, null=True)
    ultima_atualizacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Tarefa - {self.descricao}"

      
class UsuarioTarefa(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    tarefa = models.ForeignKey(Tarefa, on_delete=models.CASCADE)
    realizada = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.usuario.nome} - {self.tarefa.descricao}"      

class Avatar(models.Model):
    nome = models.CharField(max_length=100)
    url = models.CharField(max_length=255)

    def __str__(self):
        return self.nome

EcoKids/EcoKids_Integracao/views.py
import json
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from .models import Usuario, Tarefa, Forum, Avatar
from .models import Usuario, Tarefa, Forum, Avatar, UsuarioTarefa
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.db.models import Sum, Case, When, IntegerField
from django.templatetags.static import static
from datetime import timedelta


def get_avatar_url(request):
    user_avatar_url = None
    user_id = request.session.get('user_id')
    if user_id:
        try:
            usuario = Usuario.objects.get(id=user_id)
            
            if usuario.avatar_url:
                user_avatar_url = usuario.avatar_url
                print("A url do avatar é: " + user_avatar_url)
        except Usuario.DoesNotExist:
            pass
    
    return JsonResponse({'user_avatar_url': user_avatar_url})

def index(request):
    user_id = request.session.get('user_id')
    return render(request, 'EcoKids_Integracao/HomePage.html', {'user_id': user_id})


def QuemSomos(request):
    return render(request, 'EcoKids_Integracao/QuemSomos.html')

def Login(request):
    return render(request, 'EcoKids_Integracao/Login.html')

def obter_avatar_url_por_id(avatar_id):
    try:
        avatar = Avatar.objects.get(id=avatar_id)
        return avatar.url
    except Avatar.DoesNotExist:
        return None    
        
from django.urls import reverse

def Personagem(request):
    if request.method == 'POST':
        avatar_id = request.POST.get('avatar_id') 
        nome_personagem = request.POST.get('nome_personagem') 

        user_id = request.session.get('user_id')
        if user_id:
            try:
                usuario = Usuario.objects.get(id=user_id)
                usuario.personagem_selecionado = nome_personagem
                usuario.avatar_data_id = avatar_id
                avatar_url = obter_avatar_url_por_id(avatar_id)
                print("A url do avatar é: " + avatar_url)
                usuario.avatar_url = avatar_url  
                usuario.save()
                
                return JsonResponse({'avatar_url': avatar_url})

            except Usuario.DoesNotExist:
                pass

    # Definindo um cookie com a flag HttpOnly
    response = render(request, 'EcoKids_Integracao/Personagem.html')  # Substitua 'sua_pagina.html' pelo caminho da sua página
    response.set_cookie('cookie_name', 'cookie_value', httponly=True, samesite='Strict')
    return response

    return response

def Card(request):
    return render(request, 'EcoKids_Integracao/Card.html')

def ToDoList(request):
    user_id = request.session.get('user_id')
    tarefas = []

    todas_tarefas = Tarefa.objects.all()

    if user_id:
        usuario = get_object_or_404(Usuario, id=user_id)
        usuario_tarefas = UsuarioTarefa.objects.filter(usuario=usuario).select_related('tarefa')
        usuario_tarefas_dict = {ut.tarefa.id: ut.realizada for ut in usuario_tarefas}

        for tarefa in todas_tarefas:
            tarefas.append({
                'id': tarefa.id,
                'descricao': tarefa.descricao,
                'pontuacao': tarefa.pontuacao,
                'realizada': usuario_tarefas_dict.get(tarefa.id, False),
            })
    else:
        for tarefa in todas_tarefas:
            tarefas.append({
                'id': tarefa.id,
                'descricao': tarefa.descricao,
                'pontuacao': tarefa.pontuacao,
                'realizada': False, 
            })

    return render(request, 'EcoKids_Integracao/ToDoList.html', {'tarefas': tarefas})


def marcar_tarefa_realizada(request, tarefa_id):
    if request.method == 'POST':
        user_id = request.session.get('user_id')
        if user_id:
            tarefa = get_object_or_404(Tarefa, id=tarefa_id)
            usuario = get_object_or_404(Usuario, id=user_id)
            
            usuario_tarefa, created = UsuarioTarefa.objects.get_or_create(usuario=usuario, tarefa=tarefa)
            
            if not usuario_tarefa.realizada:
                usuario_tarefa.realizada = True
                usuario_tarefa.save()

                usuario.total_pontuacao += tarefa.pontuacao
                usuario.save()
            
            return JsonResponse({'success': True})
    return JsonResponse({'success': False})

def Mural(request):
    response = HttpResponse('Conteúdo da resposta')
    response.set_cookie('cookie_name', 'cookie_value', httponly=True)

    return render(request, 'EcoKids_Integracao/Mural.html')

def Login2(request):
    # Definindo um cookie com a flag HttpOnly
    response = HttpResponse('Conteúdo da resposta')
    response.set_cookie('cookie_name', 'cookie_value', httponly=True)

    if request.method == 'POST':
        data = json.loads(request.body)
        email = data.get('email').strip() 
        password = data.get('password').strip()

        try:
            user = Usuario.objects.get(email=email)
            if user.senha == password:
                request.session['user_id'] = user.id  
                return JsonResponse({'message': 'Login successful'}, status=200)
            else:
                return JsonResponse({'message': 'Invalid credentials'}, status=401)
        except Usuario.DoesNotExist:
            return JsonResponse({'message': 'User does not exist'}, status=401)
        except Exception as e:
            return JsonResponse({'message': 'An error occurred'}, status=500)
    else:
        return HttpResponseBadRequest('Method not allowed')

def signup(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        novo_usuario = Usuario(nome=nome, email=email, senha=senha)
        novo_usuario.save()

        request.session['user_id'] = novo_usuario.id

        return JsonResponse({'message': 'Usuário cadastrado com sucesso', 'success': True})
    else:
        return JsonResponse({'message': 'Método não permitido'}, status=405)



def mural_comentario(request):
    if request.method == 'POST':
        if 'user_id' in request.session:
            user_id = request.session['user_id']
            data = json.loads(request.body)
            titulo = data.get('titulo')
            comentario = data.get('comentario')
            data_hora = timezone.now()

            novo_comentario = Forum(usuario_id=user_id, titulo=titulo, comentario=comentario, data_hora=data_hora)
            novo_comentario.save()

            return JsonResponse({'message': 'Comentário adicionado com sucesso'}, status=200)
        else:
            return HttpResponseBadRequest('Unauthorized')
    else:
        comentarios = Forum.objects.order_by('-data_hora')[:10]
        comentarios_dict = [
            {'titulo': comentario.titulo, 'comentario': comentario.comentario, 'data_hora': str(comentario.data_hora)}
            for comentario in comentarios
        ]
        return JsonResponse(comentarios_dict, safe=False)


def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']  
    
    default_avatar_url = 'img/avatar-rafael.png'
    default_avatar_url = 'img/avatar-default.jpg'
    print("Logout: " + default_avatar_url)
    return JsonResponse({'user_avatar_url': default_avatar_url})


def Ranking(request):
    return render(request, 'EcoKids_Integracao/Ranking.html')



def get_ranking_data(request):
    usuarios = Usuario.objects.all().order_by('-total_pontuacao')
    data = [
        {
            "nome": usuario.nome,
            "total_pontuacao": usuario.total_pontuacao,
            "avatar_url": static(usuario.avatar_url)
        }
        for usuario in usuarios
    ]
    return JsonResponse(data, safe=False)

def verificar_atualizacao_tarefas():
    agora = timezone.now()
    tarefas = Tarefa.objects.all()
    for tarefa in tarefas:
        if (agora - tarefa.ultima_atualizacao).total_seconds() > 86400:  # 24 horas
            tarefa.ultima_atualizacao = agora
            tarefa.save()
            UsuarioTarefa.objects.filter(tarefa=tarefa).update(realizada=False)    

def get_tempo_restante(request):
    ultima_atualizacao = Tarefa.objects.latest('ultima_atualizacao').ultima_atualizacao
    agora = timezone.now()
    tempo_restante = timedelta(days=1) - (agora - ultima_atualizacao)

    if tempo_restante.total_seconds() < 0:
        tempo_restante = timedelta(seconds=0)

    return JsonResponse({'tempo_restante': int(tempo_restante.total_seconds())})            




# views.py

from django.shortcuts import render

def generate_nonce():
    import os
    import base64
    return base64.b64encode(os.urandom(16)).decode()

def Mural_Nonce(request):
    nonce = generate_nonce()
    context = {'nonce': nonce}
    return render(request, 'Mural.html', context)

def Card_Nonce(request):
    nonce = generate_nonce()
    context = {'nonce': nonce}
    return render(request, 'Card.html', context)

def HomePage_Nonce(request):
    nonce = generate_nonce()
    context = {'nonce': nonce}
    return render(request, 'HomePage.html', context)

def Personagem_Nonce(request):
    nonce = generate_nonce()
    context = {'nonce': nonce}
    return render(request, 'Personagem.html', context)

# def Login_Nonce(request):
#     nonce = generate_nonce()
#     context = {'nonce': nonce}
#     return render(request, 'Login.html', context)

# def minha_view(request):
#     # Seu código para processar a requisição...

#     # Definindo um cookie com a flag HttpOnly
#     response = HttpResponse('Conteúdo da resposta')
#     response.set_cookie('cookie_name', 'cookie_value', httponly=True)

#     return response

EcoKids/EcoKids_Integracao/templates/EcoKids_Integracao/HomePage.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EcoKids</title>
  {% load static %}
  <link rel="shortcut icon" href="{% static 'img/EcoKids-Logo.png' %}" type="image/x-icon" nonce="{{ nonce }}">

  <link rel="stylesheet" href="{% static 'css/HomePage.css' %}" nonce="{{ nonce }}">

</head>

<body>
  <div class="menu-superior">
    <div>
      <img class="EcoKids-Logo img-fluid" src="{% static 'img/EcoKids-Logo.png' %}" alt="EcoKids-Logo" nonce="{{ nonce }}">
    </div>
    <div class="barra">
      <div class="barra-colorida" style="background-color: rgba(134, 200, 154, 1);" nonce="{{ nonce }}">
        <a class="fontebarra" href="#materiais" nonce="{{ nonce }}">Materiais</a>
      </div>
      <div class="barra-colorida" style="background-color: rgba(245, 101, 124, 1);" nonce="{{ nonce }}">
        <a class="fontebarra" href="{% url 'EcoKids_Integracao:Mural' %}" nonce="{{ nonce }}">Mural</a>
      </div>
      <div class="barra-colorida" style="background-color: rgba(99, 189, 211, 1);" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:ToDoList' %}" nonce="{{ nonce }}">Metas</a>
      </div>
      <div class="barra-colorida" style="background-color: rgb(81, 235, 76);" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:Ranking' %}" nonce="{{ nonce }}">Ranking</a>
      </div>
      <div class="barra-colorida" style="background-color: rgba(201, 133, 242, 1);" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:QuemSomos' %}" nonce="{{ nonce }}">Sobre nós</a>
      </div>
      <div class="barra-colorida" style="background-color: rgba(9, 208, 168, 1);" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:Login' %}" nonce="{{ nonce }}">Login</a>
      </div>
      <div class="barra-colorida" style="background-color: rgba(235, 185, 76, 1);" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:Login' %}" id="logout_button" nonce="{{ nonce }}">Sair</a>
      </div>
    </div>
    <div nonce="{{ nonce }}">
      <p style="color: black;" id="avatar_url_placeholder" nonce="{{ nonce }}"></p>
      <a href="{% url 'EcoKids_Integracao:Personagem' %}" nonce="{{ nonce }}"><img src="" alt="Avatar do usuário" class="img-fluid" id="avatar_image" style="width: 2000; height: 100px;" nonce="{{ nonce }}"></a>
    </div>
  </div>
  <div nonce="{{ nonce }}">
    <img id="banner" src="{% static 'img/Banner.png' %}" alt="banner" class="img-fluid" nonce="{{ nonce }}">
  </div>
  <div nonce="{{ nonce }}">
    <h1 nonce="{{ nonce }}">
      <span nonce="{{ nonce }}">EQUILIBRIO ENTRE</span> BRINCAR <span nonce="{{ nonce }}">E</span> <br nonce="{{ nonce }}">APRENDER</br>
    </h1>
  </div>
  <div class="cards" nonce="{{ nonce }}">
    <a class="link-container" href="{% url 'EcoKids_Integracao:Ranking' %}" nonce="{{ nonce }}">
      <div class="cards-content bg-image-7" nonce="{{ nonce }}"></div>
    </a>
    <a href="{% url 'EcoKids_Integracao:ToDoList' %}" nonce="{{ nonce }}">
      <div class="cards-content bg-image-8" nonce="{{ nonce }}"></div>
    </a>

    <a href="{% url 'EcoKids_Integracao:Mural' %}" nonce="{{ nonce }}">
      <div class="cards-content bg-image-9" nonce="{{ nonce }}"></div>
    </a>

  </div>
  <img src="{% static 'img/Flores.png' %}" alt="Flores" class="flores" nonce="{{ nonce }}">

  <div id="materiais" nonce="{{ nonce }}">
    <div class="fundo-verde" nonce="{{ nonce }}">
      <h1 nonce="{{ nonce }}">
        EXPLORE NOSSO MUNDO!!
      </h1>
      <div class="cards" nonce="{{ nonce }}">
        <a href="{% url 'EcoKids_Integracao:Card' %}" nonce="{{ nonce }}">
          <div class="cards-content bg-image-1" nonce="{{ nonce }}"></div>
        </a>
        <div class="cards-content bg-image-2" nonce="{{ nonce }}"></div>
        <div class="cards-content bg-image-3" nonce="{{ nonce }}"></div>
        <div class="cards-content bg-image-4" nonce="{{ nonce }}"></div>
        <div class="cards-content bg-image-5" nonce="{{ nonce }}"></div>
        <div class="cards-content bg-image-6" nonce="{{ nonce }}"></div>
      </div>
    </div>
  </div>

  <img src="{% static 'img/nuvem_green_blue.png' %}" alt="nuvem" class="nuvem-green" nonce="{{ nonce }}">
  <div class="rodape" nonce="{{ nonce }}">
    <div nonce="{{ nonce }}">
      <img class="EcoKids-Logo img-fluid" src="{% static 'img/EcoKids-Logo.png' %}" alt="EcoKids-Logo" nonce="{{ nonce }}">
    </div>
    <div class="rodape-content" nonce="{{ nonce }}">
      <div nonce="{{ nonce }}">
        <h5 nonce="{{ nonce }}">SOBRE NÓS</h5>
        <a href="{% url 'EcoKids_Integracao:QuemSomos' %}" nonce="{{ nonce }}">
          <H6 nonce="{{ nonce }}">QUEM SOMOS</H6>
      </div>
      <h5 nonce="{{ nonce }}">ATENDIMENTO</h5>
      <H6 nonce="{{ nonce }}">81 9999999</H6>
    </div>
  </div>
  <img src="{% static 'img/nuvem-bottom.png' %}" alt="nuvem" class="nuvem-bottom" nonce="{{ nonce }}">
  <script src="{% static 'js/HomePage.js' %}" nonce="{{ nonce }}"></script>
  <script nonce="{{ nonce }}">
    var staticUrl = "{% static '' %}";
  </script>
  <script nonce="{{ nonce }}">
    const user_id = "{{ user_id }}";
  </script>
</body>

</html>

EcoKids/EcoKids_Integracao/templates/EcoKids_Integracao/Ranking.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Ecokids</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/Ranking.css' %}" />
  <link rel="shortcut icon" href="{% static 'img/EcoKids-Logo.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <!-- <link rel="preconnect" href="https://fonts.googleapis.com" /> -->
  <!-- <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> -->
  <!-- <link href="https://fonts.googleapis.com/css2?family=Mukta+Mahee:wght@400;700&display=swap" rel="stylesheet" /> -->
  <script defer src="{% static 'js/Ranking.js' %}"></script>
</head>

<body>

  <div class="menu-superior">
    <div>
      <a href="{% url 'EcoKids_Integracao:HomePage' %}"><img class="EcoKids-Logo img-fluid" src="{% static 'img/EcoKids-Logo.png' %}" alt="EcoKids-Logo"></a>
    </div>
    <div class="barra">
      <div class="barra-colorida " style="background-color: rgba(134, 200, 154, 1);">
        <a class="fontebarra" href="#materiais">Materiais</a>
      </div>
      <div class="barra-colorida " style="background-color: rgba(245, 101, 124, 1);"><a class="fontebarra" href="{% url 'EcoKids_Integracao:Mural' %}">Mural</a></div>
      <div class="barra-colorida " style="background-color: rgba(99, 189, 211, 1);"><a href="{% url 'EcoKids_Integracao:ToDoList' %}">Metas</a></div>
      <div class="barra-colorida " style="background-color: rgb(81, 235, 76);"><a href="{% url 'EcoKids_Integracao:Ranking' %}">Ranking</a></div>
      <div class="barra-colorida " style="background-color: rgba(201, 133, 242, 1);"><a href="{% url 'EcoKids_Integracao:QuemSomos' %}">Sobre nós</a></div>
      <div class="barra-colorida " style="background-color: rgba(9, 208, 168, 1);"><a href="{% url 'EcoKids_Integracao:Login' %}">Login</a></div>
      <div class="barra-colorida " style="background-color: rgba(235, 185, 76, 1);"><a href="{% url 'EcoKids_Integracao:Login' %}" id="logout_button">Sair</a></div>
    </div>
    <div>
      <p style="color: black;" id="avatar_url_placeholder"></p>
      <img src="" alt="Avatar do usuário" class="img-fluid" id="avatar_image" style="width: 2000; height: 100px;">
    </div>
  </div>
  <div class="container">
    <!-- <header></header> -->
    <main>
      <h4 class="titulo">RANKING</h4>
      <div class="podium">
        <ul>
          <li>
            <span>1</span>
            <img id="crown" src="{% static 'img/crown.svg' %}" alt="coroa" />
            <img data-avatar-podium src="{% static 'img/default-avatar.png' %}" alt="1° lugar" />
            <p data-name-podium>-</p>
            <span data-revenue-podium class="revenue">-</span>
          </li>
          <li data-aos="flip-right">
            <span>2</span>
            <img data-avatar-podium src="{% static 'img/default-avatar.png' %}" alt="2° lugar" />
            <p data-name-podium>-</p>
            <span data-revenue-podium class="revenue">-</span>
          </li>
          <li data-aos="flip-right">
            <span>3</span>
            <img data-avatar-podium src="{% static 'img/default-avatar.png' %}" alt="3° lugar" />
            <p data-name-podium>-</p>
            <span data-revenue-podium class="revenue">-</span>
          </li>
        </ul>
      </div>
    </main>
    <section>
      <span>O ranking é atualizado a cada 1 minuto.</span>
      <ul data-aos="fade-right">
        <li>
          <span>1</span>
          <img data-avatar src="{% static 'img/default-avatar.png' %}" alt="" />
          <p data-name>-</p>
          <span data-revenue class="revenue">-</span>
        </li>
        <li>
          <span>2</span>
          <img data-avatar src="{% static 'img/default-avatar.png' %}" alt="" />
          <p data-name>-</p>
          <span data-revenue class="revenue">-</span>
        </li>
        <li>
          <span>3</span>
          <img data-avatar src="{% static 'img/default-avatar.png' %}" alt="" />
          <p data-name>-</p>
          <span data-revenue class="revenue">-</span>
        </li>
        <li>
          <span>4</span>
          <img data-avatar src="{% static 'img/default-avatar.png' %}" alt="" />
          <p data-name>-</p>
          <span data-revenue class="revenue">-</span>
        </li>
        <li>
          <span>5</span>
          <img data-avatar src="{% static 'img/default-avatar.png' %}" alt="" />
          <p data-name>-</p>
          <span data-revenue class="revenue">-</span>
        </li>
      </ul>
    </section>
  </div>



  <img src="{% static 'img/nuvem-top-white.png' %}" alt="nuvem" class="nuvem-green">
  <div class="rodape">
    <div>
      <img class="EcoKids-Logo img-fluid" src="{% static 'img/EcoKids-Logo.png' %}" alt="EcoKids-Logo">
    </div>
    <div class="rodape-content">
      <div>
        <h5>SOBRE NÓS</h5>
        <a href="{% url 'EcoKids_Integracao:QuemSomos' %}">
          <H6>QUEM SOMOS</H6>
      </div>
      <!-- <div>
        <h5>SOBRE NÓS</h5>
        <a href="{% url 'EcoKids_Integracao:Personagem' %}">
          <H6>Personagem</H6>
        </a>
      </div>
      <div> -->
      <h5>ATENDIMENTO</h5>
      <!-- <a href="{% url 'EcoKids_Integracao:QuemSomos' %}"> -->
      <H6>81 9999999</H6>
      </a>
    </div>
  </div>
  </div>
  <img src="{% static 'img/nuvem-bottom.png' %}" alt="nuvem" class="nuvem-bottom">

  <script src="{% static 'js/Ranking-animacao.js' %}"></script>
  <script nonce="{{ nonce }}">
    AOS.init({
      duration: 1000,
      once: true,
    });
  </script>
  <script nonce="{{ nonce }}">
    var staticUrl = "{% static '' %}";
  </script>
  <script src="{% static 'js/logout.js' %}" nonce="{{ nonce }}"></script>
</body>

</html>